#!/bin/bash

options="󰍃  Logout\n󰤄  Suspend\n  Reboot\n  Power Off"

chosen=$(echo -e "$options" | rofi -dmenu -i -theme ~/.config/rofi/config_power.rasi)

case "$chosen" in
  *Power\ Off) systemctl poweroff ;;
  *Reboot) systemctl reboot ;;
  *Suspend) systemctl suspend ;;
  *Logout) swaymsg exit || pkill -KILL -u $USER ;;
esac

